[package]
name = "screenie-sharer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.6.1", features = [] }
cc = "=1.2.25"

[dependencies]
tauri = { version = "=2.11.1", features = [] }
tokio = { version = "=1.52.3", features = ["rt-multi-thread", "macros", "sync"] }
tokio-tungstenite = { version = "=0.29.0", features = ["native-tls"] }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.149"
url = "=2.5.8"
futures-util = "=0.3.32"
x11rb = { version = "=0.13.2", features = ["randr", "render", "shm", "image"] }
webrtc = "=0.8.0"
interceptor = "=0.9.0"
enigo = "=0.6.1"
log = "=0.4.27"
tauri-plugin-global-shortcut = "=2.3.1"
